"""中文术语表与动作词根词典。

全部映射均为「英文 → 中文」的纯函数数据，不依赖任何运行时状态，
保证译名流水线幂等可重算。

分区：
  1. DIMENSIONS   —— 四个筛选维度（部位/器械/目标肌群/协同肌群）
  2. NOISE        —— 必须丢弃的噪声词（性别、机位标记）
  3. TYPO_FIX     —— 数据集中的拼写错误
  4. TERMS        —— 动作词根 / 修饰语 / 器械 / 身体词，最长匹配优先
  5. OVERRIDE     —— 人工指定译名（最高优先级，按 id 索引）
"""

from __future__ import annotations

# ---------------------------------------------------------------- 1. 维度

BODY_PART_ZH = {
    "upper arms": "上臂",
    "upper legs": "大腿",
    "back": "背部",
    "waist": "腰腹",
    "chest": "胸部",
    "shoulders": "肩部",
    "lower legs": "小腿",
    "lower arms": "前臂",
    "cardio": "有氧",
    "neck": "颈部",
}

EQUIPMENT_ZH = {
    "body weight": "徒手",
    "dumbbell": "哑铃",
    "cable": "绳索",
    "barbell": "杠铃",
    "leverage machine": "器械",
    "band": "弹力带",
    "smith machine": "史密斯机",
    "kettlebell": "壶铃",
    "weighted": "负重",
    "stability ball": "健身球",
    "ez barbell": "曲杆",
    "assisted": "助力",
    "sled machine": "雪橇机",
    "medicine ball": "药球",
    "rope": "战绳",
    "roller": "滚轮",
    "resistance band": "阻力带",
    "bosu ball": "波速球",
    "olympic barbell": "奥杆",
    "wheel roller": "健腹轮",
    "upper body ergometer": "上肢功率车",
    "skierg machine": "滑雪机",
    "hammer": "锤式",
    "stationary bike": "健身车",
    "tire": "轮胎",
    "trap bar": "六角杠",
    "elliptical machine": "椭圆机",
    "stepmill machine": "台阶机",
}

# 器械大类（派生维度，用于「动作类型」筛选）
EQUIPMENT_GROUP = {
    "body weight": "徒手",
    "weighted": "徒手",
    "assisted": "徒手",
    "dumbbell": "自由重量",
    "barbell": "自由重量",
    "ez barbell": "自由重量",
    "olympic barbell": "自由重量",
    "trap bar": "自由重量",
    "kettlebell": "自由重量",
    "band": "弹力带",
    "resistance band": "弹力带",
    "cable": "绳索滑轮",
    "rope": "绳索滑轮",
    "leverage machine": "固定器械",
    "smith machine": "固定器械",
    "sled machine": "固定器械",
    "hammer": "固定器械",
    "stationary bike": "有氧器械",
    "elliptical machine": "有氧器械",
    "stepmill machine": "有氧器械",
    "skierg machine": "有氧器械",
    "upper body ergometer": "有氧器械",
    "tire": "其他",
    "medicine ball": "其他",
    "stability ball": "其他",
    "bosu ball": "其他",
    "roller": "其他",
    "wheel roller": "其他",
}

TARGET_ZH = {
    "abs": "腹直肌",
    "pectorals": "胸大肌",
    "biceps": "肱二头肌",
    "glutes": "臀大肌",
    "delts": "三角肌",
    "triceps": "肱三头肌",
    "upper back": "上背",
    "lats": "背阔肌",
    "calves": "小腿三头肌",
    "quads": "股四头肌",
    "forearms": "前臂",
    "cardiovascular system": "心肺系统",
    "hamstrings": "腘绳肌",
    "spine": "竖脊肌",
    "traps": "斜方肌",
    "adductors": "内收肌",
    "serratus anterior": "前锯肌",
    "abductors": "外展肌",
    "levator scapulae": "肩胛提肌",
}

MUSCLE_ZH = {
    "shoulders": "三角肌",
    "forearms": "前臂",
    "biceps": "肱二头肌",
    "triceps": "肱三头肌",
    "hamstrings": "腘绳肌",
    "quadriceps": "股四头肌",
    "glutes": "臀大肌",
    "obliques": "腹斜肌",
    "hip flexors": "髂腰肌",
    "chest": "胸大肌",
    "trapezius": "斜方肌",
    "traps": "斜方肌",
    "deltoids": "三角肌",
    "calves": "小腿三头肌",
    "ankles": "踝关节",
    "core": "核心",
    "lower back": "下背",
    "rotator cuff": "肩袖",
    "soleus": "比目鱼肌",
    "rhomboids": "菱形肌",
    "wrist flexors": "腕屈肌",
    "latissimus dorsi": "背阔肌",
    "abdominals": "腹直肌",
    "ankle stabilizers": "踝稳定肌",
    "upper back": "上背",
    "wrist extensors": "腕伸肌",
    "lats": "背阔肌",
    "wrists": "腕关节",
    "hands": "手部",
}

# ---------------------------------------------------------------- 2. 噪声

NOISE_TOKENS = {
    "male", "female", "the", "a", "an", "of", "in", "from",
    "variation", "version",
}

# 噪声短语（括号整体丢弃）
NOISE_PHRASES = {
    "male", "female", "pov", "male version", "female version", "equipment",
}

# ---------------------------------------------------------------- 3. 拼写纠正

TYPO_FIX = {
    "sitted": "seated",
    "peacher": "preacher",
    "keens": "knees",
    "revers": "reverse",
    "rollerer": "roller",
    "supper": "superman",
    "dips": "dip",
    "curls": "curl",
    "raises": "raise",
    "squats": "squat",
    "jumps": "jump",
    "kicks": "kick",
    "knees": "knee",
    "legs": "leg",
    "arms": "arm",
    "hands": "hand",
    "palms": "palm",
    "ankles": "ankle",
    "calves": "calf",
    "quads": "quad",
    "traps": "trap",
    "glutes": "glute",
    "flyes": "fly",
    "crunches": "crunch",
    "twists": "twist",
    "sprints": "sprint",
    "hops": "hop",
    "kickbacks": "kickback",
    "presses": "press",
    "thrusts": "thrust",
    "bends": "bend",
    "feet": "foot",
    "toes": "toe",
    "hips": "hip",
    "gripper": "grip",
    "dumbbells": "dumbbell",
    "ropes": "rope",
    "bars": "bar",
    "crossovers": "crossover",
    "circles": "circle",
}

# ---------------------------------------------------------------- 4. 术语

# 动作词根（主体动作）——优先级最高，最长匹配
MOVEMENTS = {
    "good morning": "早安式",
    "mountain climber": "登山跑",
    "jumping jack": "开合跳",
    "jack jump": "开合跳",
    "star jump": "星式跳",
    "box jump": "跳箱",
    "tuck jump": "团身跳",
    "split jump": "分腿跳",
    "scissor jump": "剪式跳",
    "astride jump": "分腿跳",
    "burpee": "波比跳",
    "thruster": "推举深蹲",
    "clean and jerk": "挺举",
    "clean": "高翻",
    "snatch": "抓举",
    "jerk": "挺举",
    "deadlift": "硬拉",
    "romanian deadlift": "罗马尼亚硬拉",
    "stiff leg deadlift": "直腿硬拉",
    "pull through": "穿越拉",
    "face pull": "面拉",
    "lat pulldown": "背阔肌下拉",
    "pulldown": "下拉",
    "pushdown": "下压",
    "pullover": "仰卧上拉",
    "push up": "俯卧撑",
    "pull up": "引体向上",
    "chin up": "反握引体向上",
    "sit up": "仰卧起坐",
    "step up": "登台阶",
    "hip thrust": "臀推",
    "glute bridge": "臀桥",
    "leg press": "腿举",
    "bench press": "卧推",
    "shoulder press": "肩推",
    "chest press": "胸推",
    "military press": "军式推举",
    "overhead press": "过头推举",
    "arnold press": "阿诺德推举",
    "skull crusher": "碎颅者",
    "skullcrusher": "碎颅者",
    "preacher curl": "牧师凳弯举",
    "concentration curl": "集中弯举",
    "hammer curl": "锤式弯举",
    "wrist curl": "腕弯举",
    "wrist extension": "腕伸展",
    "bicep curl": "肱二头肌弯举",
    "tricep extension": "肱三头肌伸展",
    "leg extension": "腿屈伸",
    "leg curl": "腿弯举",
    "calf raise": "提踵",
    "leg raise": "抬腿",
    "knee raise": "抬膝",
    "lateral raise": "侧平举",
    "front raise": "前平举",
    "rear delt": "后束",
    "back extension": "背部伸展",
    "hyperextension": "山羊挺身",
    "hip abduction": "髋外展",
    "hip adduction": "髋内收",
    "reverse crunch": "反向卷腹",
    "bicycle crunch": "自行车卷腹",
    "russian twist": "俄罗斯转体",
    "toe touch": "体前屈",
    "calf stretch": "小腿拉伸",
    "chest stretch": "胸部拉伸",
    "back stretch": "背部拉伸",
    "quad stretch": "股四头肌拉伸",
    "hip stretch": "髋部拉伸",
    "hamstring stretch": "腘绳肌拉伸",
    "front squat": "前蹲",
    "hack squat": "哈克深蹲",
    "goblet squat": "高脚杯深蹲",
    "sumo squat": "相扑深蹲",
    "split squat": "分腿蹲",
    "pistol squat": "单腿深蹲",
    "sissy squat": "西斯深蹲",
    "zercher squat": "泽奇深蹲",
    "box squat": "箱式深蹲",
    "jump squat": "蹲跳",
    "wall sit": "靠墙静蹲",
    "potty squat": "蹲式",
    "side plank": "侧平板支撑",
    "plank": "平板支撑",
    "bear crawl": "熊爬",
    "inchworm": "尺蠖式",
    "superman": "超人式",
    "windmill": "风车式",
    "jackknife": "折叠式",
    "cossack": "哥萨克",
    "curtsey": "屈膝礼",
    "skater": "滑冰式",
    "swimmer": "游泳式",
    "sphinx": "狮身式",
    "cobra": "眼镜蛇式",
    "cat": "猫式",
    "crab": "蟹行",
    "frog": "蛙式",
    "donkey": "驴式",
    "pike": "屈体",
    "planche": "俄式挺身",
    "maltese": "马耳他十字",
    "handstand": "倒立",
    "crossover": "交叉夹胸",
    "cross over": "交叉夹胸",
    "cross": "交叉",
    "fly": "飞鸟",
    "row": "划船",
    "shrug": "耸肩",
    "squat": "深蹲",
    "lunge": "弓步",
    "dip": "臂屈伸",
    "crunch": "卷腹",
    "twist": "转体",
    "stretch": "拉伸",
    "raise": "上举",
    "extension": "伸展",
    "curl": "弯举",
    "press": "推举",
    "pull": "拉",
    "push": "推",
    "jump": "跳跃",
    "hop": "跳",
    "run": "跑步",
    "sprint": "冲刺",
    "walk": "行走",
    "march": "踏步",
    "crawl": "爬行",
    "climb": "攀爬",
    "throw": "投掷",
    "slam": "砸球",
    "kickback": "后踢",
    "kick": "踢腿",
    "bridge": "臀桥",
    "swing": "摆荡",
    "rotation": "旋转",
    "rotate": "旋转",
    "lift": "提举",
    "reach": "伸展",
    "touch": "触",
    "pass": "传递",
    "flip": "翻转",
    "hang": "悬垂",
    "hold": "保持",
    "carry": "提行",
    "squeeze": "夹",
    "circles": "绕环",
    "circle": "绕环",
    "arc": "弧线",
    "tilt": "倾斜",
    "flexion": "屈曲",
    "adduction": "内收",
    "abduction": "外展",
    "pronation": "旋前",
    "supination": "旋后",
    "pronate": "旋前",
    "stabilization": "稳定",
    "drop": "下放",
    "release": "释放",
    "catch": "接",
    "saw": "锯式",
    "crusher": "碎颅",
    "blaster": "臂托",
    "gripper": "握力",
    "gripless": "无握",
    "hook": "钩式",
    "squeeze": "挤压",
    "tap": "拍击",
    "clap": "击掌",
    "flutter": "打水",
    "scissor": "剪式",
    "wipers": "雨刷式",
    "cocoons": "蚕茧式",
    "seesaw": "跷跷板式",
    "elevator": "升降式",
    "flag": "旗帜式",
    "judo": "柔道",
    "boxing": "拳击",
    "kayak": "皮划艇",
    "bowling": "保龄球",
    "tennis": "网球",
    "yoga": "瑜伽",
    "pose": "体式",
}

# 姿态 / 修饰语
MODIFIERS = {
    "seated": "坐姿",
    "standing": "站姿",
    "lying": "仰卧",
    "prone": "俯卧",
    "supine": "仰卧",
    "kneeling": "跪姿",
    "squatting": "蹲姿",
    "sitting": "坐姿",
    "incline": "上斜",
    "decline": "下斜",
    "flat": "平躺",
    "reverse": "反向",
    "bent over": "俯身",
    "bent": "屈",
    "close grip": "窄距",
    "narrow grip": "窄距",
    "wide grip": "宽距",
    "neutral grip": "中立握",
    "reverse grip": "反握",
    "straight arm": "直臂",
    "straight leg": "直腿",
    "straight back": "直背",
    "straight": "直",
    "single leg": "单腿",
    "one leg": "单腿",
    "single arm": "单臂",
    "one arm": "单臂",
    "two leg": "双腿",
    "two arm": "双臂",
    "both leg": "双腿",
    "alternating": "交替",
    "alternate": "交替",
    "unilateral": "单侧",
    "contralateral": "对侧",
    "isometric": "等长",
    "dynamic": "动态",
    "negative": "退让",
    "plyo": "增强式",
    "explosive": "爆发式",
    "overhead": "过头",
    "upright": "直立",
    "inverted": "倒立",
    "elevated": "垫高",
    "suspended": "悬挂",
    "supported": "支撑",
    "assisted": "助力",
    "weighted": "负重",
    "modified": "改良",
    "advanced": "进阶",
    "intermediate": "中级",
    "basic": "基础",
    "full": "全程",
    "half": "半程",
    "quarter": "四分之一",
    "deep": "深度",
    "high": "高",
    "low": "低",
    "short": "短",
    "wide": "宽",
    "narrow": "窄",
    "close": "窄",
    "straight": "直",
    "bent": "屈",
    "extended": "伸展",
    "raised": "抬高",
    "crossed": "交叉",
    "clasped": "交叉握",
    "reversed": "反向",
    "rotated": "旋转",
    "angled": "斜角",
    "fixed": "固定",
    "horizontal": "水平",
    "vertical": "垂直",
    "parallel": "平行",
    "diagonal": "对角",
    "circular": "环绕",
    "rotational": "旋转",
    "internal": "内旋",
    "external": "外旋",
    "mixed": "混合",
    "mixed grip": "混合握",
    "overhand": "正握",
    "underhand": "反握",
    "pronated": "正握",
    "supinated": "反握",
    "neutral": "中立",
    "double": "双",
    "twin": "双",
    "three": "三",
    "two": "双",
    "one": "单",
    "single": "单",
    "left": "左",
    "right": "右",
    "both": "双侧",
    "inside": "内侧",
    "outside": "外侧",
    "inner": "内侧",
    "outer": "外侧",
    "upper": "上",
    "lower": "下",
    "middle": "中",
    "front": "前",
    "rear": "后",
    "side": "侧",
    "posterior": "后侧",
    "lateral": "侧向",
    "behind": "背后",
    "forward": "向前",
    "backward": "向后",
    "upward": "向上",
    "downward": "向下",
    "outward": "向外",
    "against": "靠",
    "around": "环绕",
    "between": "之间",
    "over": "越过",
    "under": "下方",
    "through": "穿过",
    "above": "上方",
    "across": "横跨",
    "into": "成",
    "from": "自",
    "to": "至",
    "with": "用",
    "and": "与",
    "on": "于",
    "off": "离",
    "out": "出",
    "apart": "分开",
    "closer": "更近",
    "together": "并拢",
    "facing": "朝向",
    "depth": "深度",
    "angle": "角度",
    "degrees": "度",
    "point": "点",
    "position": "位",
    "motion": "动作",
    "range": "幅度",
    "sequence": "序列",
    "style": "式",
    "reps": "次",
    "multiple": "多次",
    "response": "反应",
    "quick": "快速",
    "speed": "速度",
    "power": "爆发",
    "gravity": "重力",
    "self": "自体",
    "anti": "抗",
    "rocking": "摇摆",
    "swing": "摆荡",
    "plyometric": "增强式",
}

# 身体词
BODY_WORDS = {
    "arm": "臂",
    "leg": "腿",
    "calf": "小腿",
    "knee": "膝",
    "hip": "髋",
    "chest": "胸",
    "shoulder": "肩",
    "back": "背",
    "neck": "颈",
    "wrist": "腕",
    "elbow": "肘",
    "head": "头",
    "hand": "手",
    "palm": "掌",
    "finger": "指",
    "toe": "趾",
    "ankle": "踝",
    "foot": "足",
    "thigh": "大腿",
    "glute": "臀",
    "waist": "腰",
    "torso": "躯干",
    "body": "身体",
    "chest": "胸",
    "abs": "腹肌",
    "ab": "腹",
    "core": "核心",
    "spine": "脊柱",
    "scapula": "肩胛",
    "scapular": "肩胛",
    "sternum": "胸骨",
    "groin": "腹股沟",
    "pelvic": "骨盆",
    "bicep": "肱二头肌",
    "tricep": "肱三头肌",
    "delt": "三角肌",
    "deltoid": "三角肌",
    "lat": "背阔肌",
    "hamstring": "腘绳肌",
    "quad": "股四头肌",
    "oblique": "腹斜肌",
    "pec": "胸肌",
    "trap": "斜方肌",
    "trapezius": "斜方肌",
    "rhomboids": "菱形肌",
    "soleus": "比目鱼肌",
    "piriformis": "梨状肌",
    "femoral": "股",
    "tibialis": "胫骨肌",
    "peroneals": "腓骨肌",
    "adductor": "内收肌",
    "abductor": "外展肌",
    "flexor": "屈肌",
    "extensors": "伸肌",
    "quadriceps": "股四头肌",
    "gluteus": "臀肌",
    "muscle": "肌肉",
    "hip flexors": "髂腰肌",
    "lower back": "下背",
    "upper back": "上背",
    "rotator cuff": "肩袖",
    "wrist flexors": "腕屈肌",
    "wrist extensors": "腕伸肌",
    "latissimus dorsi": "背阔肌",
    "rectus femoris": "股直肌",
    "pectoralis major": "胸大肌",
    "serratus anterior": "前锯肌",
    "levator scapulae": "肩胛提肌",
    "hip flexor": "髂腰肌",
    "heart": "心脏",
    "cardiovascular": "心肺",
}

# 器械 / 场地 / 器材（出现在名称中的）
GEAR_WORDS = {
    "dumbbell": "哑铃",
    "barbell": "杠铃",
    "cable": "绳索",
    "kettlebell": "壶铃",
    "band": "弹力带",
    "resistance": "阻力",
    "smith": "史密斯",
    "lever": "器械",
    "machine": "器械",
    "sled": "雪橇",
    "rope": "绳",
    "ball": "球",
    "medicine": "药球",
    "stability": "健身球",
    "bosu": "波速球",
    "roller": "滚轮",
    "wheel": "健腹轮",
    "ez": "曲杆",
    "bar": "杠",
    "bench": "凳",
    "floor": "地面",
    "wall": "墙",
    "chair": "椅",
    "box": "箱",
    "stepbox": "踏板",
    "stepmill": "台阶机",
    "treadmill": "跑步机",
    "bike": "单车",
    "cycle": "单车",
    "elliptical": "椭圆机",
    "ergometer": "功率车",
    "ski": "滑雪",
    "skierg": "滑雪机",
    "step": "台阶",
    "platform": "台",
    "pad": "垫",
    "towel": "毛巾",
    "ring": "吊环",
    "rack": "架",
    "cage": "框",
    "board": "板",
    "tire": "轮胎",
    "sledge": "雪橇",
    "hammer": "锤",
    "pulley": "滑轮",
    "attachment": "附件",
    "handle": "握把",
    "strap": "拉带",
    "blaster": "臂托",
    "stirrups": "马镫把手",
    "bodyweight": "自重",
    "body weight": "徒手",
    "trap": "六角杠",
    "olympic": "奥杆",
    "landmine": "地雷管",
    "slingers": "吊带",
    "ground": "地面",
    "hands": "手",
}

# 专有名词（人名 / 流派，音译）
PROPER_NOUNS = {
    "arnold": "阿诺德",
    "cuban": "古巴",
    "zottman": "佐特曼",
    "bradford": "布拉德福德",
    "gironda": "吉龙达",
    "romanian": "罗马尼亚",
    "hack": "哈克",
    "sissy": "西斯",
    "goblet": "高脚杯",
    "sumo": "相扑",
    "zercher": "泽奇",
    "jefferson": "杰斐逊",
    "pallof": "帕洛夫",
    "copenhagen": "哥本哈根",
    "turkish": "土耳其",
    "london": "伦敦",
    "rocky": "洛奇",
    "otis": "奥蒂斯",
    "tate": "泰特",
    "thibaudeau": "蒂博多",
    "frankenstein": "弗兰肯斯坦",
    "gorilla": "大猩猩",
    "spider": "蜘蛛",
    "dragon": "龙旗",
    "scott": "斯科特",
    "sz": "曲杆",
    "korean": "韩国",
    "hindu": "印度",
    "maltese": "马耳他",
    "bradford": "布拉德福德",
    "jm": "JM",
    "svend": "斯文德",
    "gironda": "吉龙达",
    "janda": "扬达",
    "renegade": "叛徒",
    "thibaudeau": "蒂博多",
    "pendlay": "彭德雷",
    "sz": "曲杆",
    "guillotine": "断头台式",
    "skull": "碎颅",
    "zercher": "泽奇",
}

# ---------------------------------------------------------------- 4b. 补充

# 第二轮补齐：覆盖首轮未译词（含复数形、专有流派、整体短语）
MOVEMENTS.update({
    "battling ropes": "战绳",
    "dead bug": "死虫式",
    "all fours": "四肢着地",
    "heel touchers": "触踵",
    "heel toucher": "触踵",
    "figure 8": "8字",
    "turkish get up": "土耳其起立",
    "get up": "起立",
    "monster walk": "怪兽行走",
    "iron cross": "铁十字",
    "farmers walk": "农夫行走",
    "captains chair": "队长椅",
    "skin the cat": "猫式翻越",
    "impossible dip": "极限臂屈伸",
    "air bike": "空中单车",
    "butt lift": "提臀",
    "stork stance": "鹳式站姿",
    "spell caster": "施法者",
    "pin press": "定位推举",
    "one legged": "单腿",
    "v up": "V字两头起",
    "l sit": "L字支撑",
    "bend": "屈",
    "sit": "坐",
    "tuck": "团身",
    "hyper": "挺身",
    "drag": "拖拽",
    "hug": "抱",
    "straddle": "分腿",
    "drive": "驱动",
    "kipping": "摆荡式",
    "slide": "滑行",
    "fallout": "前伸",
    "round": "圆背",
    "wind": "绕环",
    "butterfly": "蝶式",
    "lean": "倾斜",
    "stride": "跨步",
    "waiter": "侍者式",
    "pistol": "单腿深蹲",
    "prisoner": "囚徒",
    "plus": "加强",
    "rotary": "旋转",
    "stork": "鹳式",
    "jack": "开合",
    "lifting": "提举",
    "archer": "射手",
    "french": "法式",
    "inverse": "反向",
    "rollerout": "健腹轮",
    "battling": "战",
    "cambered": "弧形",
    "clock": "时钟",
    "bug": "虫式",
    "diamond": "钻石",
    "pirate": "海盗",
    "monster": "怪兽",
    "spell": "施法",
    "caster": "施法者",
    "knife": "折叠",
    "pyramid": "金字塔",
    "dog": "犬式",
    "staircase": "阶梯",
    "squad": "队",
    "runners": "跑者",
    "pin": "定位",
    "farmers": "农夫",
    "captains": "队长",
    "impossible": "极限",
    "skin": "皮肤",
    "outstretched": "伸展",
    "forth": "前后",
    "balance": "平衡",
    "support": "支撑",
    "iron": "铁",
    "face": "面",
    "pro": "专业",
    "world": "世界",
    "can": "罐",
    "butt": "臀",
    "big": "大",
    "greatest": "最大",
    "semi": "半",
    "fours": "四足",
    "air": "空中",
    "heel": "跟",
    "touchers": "触",
    "get": "起",
    "breeding": "繁殖",
})

MODIFIERS.update({
    "hanging": "悬垂",
    "twisting": "转体",
    "twisted": "转体",
    "walking": "行走",
    "stance": "站姿",
    "reclining": "斜躺",
    "stiff": "直",
    "abdominal": "腹部",
    "benches": "凳",
    "legged": "腿",
    "grip": "握",
    "chin": "引体",
    "up": "上",
    "down": "下",
    "y": "Y字",
    "t": "T字",
    "v": "V字",
    "w": "W字",
    "l": "L字",
})

BODY_WORDS.update({
    "triceps": "肱三头肌",
    "biceps": "肱二头肌",
    "ham": "腘绳肌",
    "knees": "膝",
    "butt": "臀",
})

PROPER_NOUNS.update({
    "hyght": "海特",
    "stalder": "施塔尔德",
})

TYPO_FIX.update({
    "ups": "up",
    "tricep": "triceps",
    "bicep": "biceps",
    "bottoms": "bottom",
    "depresor": "depressor",
})

MOVEMENTS.update({
    "bottoms up": "托举",
    "bottom up": "托举",
    "arm blaster": "臂托",
    "knee bend": "屈膝",
    "knee bends": "屈膝",
    "palms in": "掌心相对",
    "palms out": "掌心向外",
    "t-bar": "T杠",
    "throw down": "下投",
    "saw": "锯式",
    "ski step": "滑雪踏步",
    "front lever": "前水平",
    "back lever": "后水平",
    "front lever reps": "前水平保持",
    "wheel run": "健腹轮推行",
    "side to side": "左右",
    "side lying": "侧卧",
    "knee bent": "屈膝",
    "bent knee": "屈膝",
    "back pov": "后视角",
    "side pov": "侧视角",
    "front pov": "前视角",
    "trainer": "训练器",
    "depressor": "下压肌",
    "retractor": "后缩肌",
    "skier": "滑雪者",
    "concentration": "集中",
    "preacher": "牧师凳",
    "straps": "拉带",
})

# 器械剥离项：映射为空串，作为最长匹配项参与翻译，避免先剥后译拆散短语
EQUIP_STRIP_PHRASES = {
    "trap bar", "ez barbell", "resistance band", "stability ball", "medicine ball",
    "bosu ball", "exercise ball", "wheel roller", "smith machine", "leverage machine",
    "sled machine", "skierg machine", "stepmill machine", "elliptical machine",
    "stationary bike", "upper body ergometer", "olympic barbell", "body weight",
    "cable rope",
}
EQUIP_STRIP_WORDS = {
    "dumbbell", "barbell", "cable", "kettlebell", "band", "smith", "machine", "lever",
    "leverage", "ez", "sled", "roller", "wheel", "weighted", "assisted", "bodyweight",
    "tire", "sledge", "skierg", "stepmill", "elliptical", "stationary", "bosu",
    "ergometer", "bike", "cycle", "ball", "olympic", "equipment", "exercise",
    "pov",
}

# 合并所有词条（后面的分区优先级低于前面的分区，通过匹配顺序控制）
ALL_TERMS = {}
for _src in (MOVEMENTS, MODIFIERS, BODY_WORDS, GEAR_WORDS, PROPER_NOUNS):
    for _k, _v in _src.items():
        ALL_TERMS.setdefault(_k, _v)

# 器械剥离项强制覆盖为「空译名」，使其在最长匹配中优先吃掉器械词
for _p in EQUIP_STRIP_PHRASES:
    ALL_TERMS[_p] = ""
for _w in EQUIP_STRIP_WORDS:
    ALL_TERMS[_w] = ""

# 限定语专用词表：括号内容里的器械词必须保留，
# 否则「(on stability ball)」会退化成空串，导致两条不同动作撞名。
_QUAL_KEEP = {
    "stability ball": "健身球", "bosu ball": "波速球", "medicine ball": "药球",
    "exercise ball": "健身球", "resistance band": "阻力带", "trap bar": "六角杠",
    "ez barbell": "曲杆", "smith machine": "史密斯机", "leverage machine": "器械",
    "sled machine": "雪橇机", "olympic barbell": "奥杆", "body weight": "徒手",
    "wheel roller": "健腹轮", "skierg machine": "滑雪机", "stepmill machine": "台阶机",
    "elliptical machine": "椭圆机", "stationary bike": "健身车",
    "upper body ergometer": "上肢功率车",
    "knee": "跪姿",
}
ALL_TERMS_QUAL = dict(ALL_TERMS)
for _p, _zh in _QUAL_KEEP.items():
    ALL_TERMS_QUAL[_p] = _zh
for _w in EQUIP_STRIP_WORDS:
    if _w in GEAR_WORDS:
        ALL_TERMS_QUAL[_w] = GEAR_WORDS[_w]
    elif _w in EQUIPMENT_ZH:
        ALL_TERMS_QUAL[_w] = EQUIPMENT_ZH[_w]

# ---------------------------------------------------------------- 5. 人工覆盖

# 按 id 指定译名（最高优先级）。id 必须存在于种子数据，否则流水线报错退出。
# 命名约定：来源数据里有些近重复条目（英文名仅一词之差，但其实是不同变体），
# 用以下精确译名消歧。完全相同的英文名仍保留「（2）」以提示源数据重复。
OVERRIDE_BY_ID: dict[str, str] = {
    # 重复条目 / 语义特例的人工定名
    "0684": "器械跑步",
    "0685": "跑步",

    # ---- 22 组近重复条目的精确消歧 ----
    # lever bent over row / lever one arm bent over row：lever = T杠（杠铃配件），
    # 与普通 barbell 杠铃俯身划船相区分。
    "0027": "杠铃俯身划船",
    "0574": "T杠俯身划船",
    "0064": "杠铃单臂俯身划船",
    "0589": "T杠单臂俯身划船",

    # lever chest press：完全重复，保留序号。
    "0576": "器械胸推",
    "0577": "器械胸推（2）",

    # cable rope * vs cable *：rope=双绳头（两端绳），普通 cable 单头；明确区分。
    "0861": "绳索坐姿划船",
    "1323": "双绳坐姿划船",
    "0173": "绳索上斜肱三头肌伸展",
    "1725": "双绳上斜肱三头肌伸展",
    "1722": "绳索高滑轮过头肱三头肌伸展",
    "1724": "双绳高滑轮过头肱三头肌伸展",

    # push-up (bosu ball) / push up on bosu ball：同义重复，保留序号。
    "0653": "波速球俯卧撑",
    "1307": "波速球俯卧撑（2）",

    # push-up (on stability ball) 完全重复。
    "0655": "健身球俯卧撑",
    "0656": "健身球俯卧撑（2）",

    # reverse grip pull-up vs chin-up：chin-up 严格定义为正握（underhand），
    # 故译「正握引体向上」。
    "0674": "反握引体向上",
    "1326": "正握引体向上",

    # barbell seated calf raise 完全重复。
    "0088": "杠铃坐姿提踵",
    "1371": "杠铃坐姿提踵（2）",

    # smith reverse calf raises 完全重复。
    "0763": "史密斯机反向提踵",
    "1394": "史密斯机反向提踵（2）",

    # ez barbell spider curl 完全重复。
    "0454": "曲杆蜘蛛弯举",
    "1628": "曲杆蜘蛛弯举（2）",

    # self assisted inverse leg curl 完全重复。
    "0697": "自体反向腿弯举",
    "1766": "自体反向腿弯举（2）",

    # dumbbell stiff leg deadlift（罗马尼亚硬拉）vs dumbbell straight leg deadlift（直腿硬拉）。
    "0432": "哑铃罗马尼亚硬拉",
    "0434": "哑铃直腿硬拉",
    # band stiff leg deadlift vs band straight leg deadlift 同理。
    "1009": "弹力带罗马尼亚硬拉",
    "1010": "弹力带直腿硬拉",

    # dumbbell single leg calf raise / single leg calf raise (on a dumbbell)：同义重复。
    "0409": "哑铃单腿提踵",
    "0727": "哑铃单腿提踵（2）",

    # dumbbell lying triceps extension vs exercise ball supine triceps extension：
    # v2 是在健身球上完成仰卧肱三头肌伸展。
    "0351": "哑铃仰卧肱三头肌伸展",
    "1746": "健身球仰卧肱三头肌伸展",

    # dumbbell lying pullover on exercise ball / dumbbell pullover on exercise ball：
    # 同义重复。
    "1284": "哑铃仰卧上拉（健身球）",
    "1295": "哑铃仰卧上拉（健身球）（2）",

    # dumbbell close-grip press / dumbbell close grip press：同义重复。
    "0296": "哑铃窄距推举",
    "1731": "哑铃窄距推举（2）",

    # dumbbell seated triceps extension / dumbbells seated triceps extension：
    # 单手 vs 双手双哑铃。
    "2188": "哑铃坐姿肱三头肌伸展",
    "2189": "双哑铃坐姿肱三头肌伸展",

    # barbell sitted alternate leg raise / ... (female)：男女版本差异。
    "2799": "杠铃坐姿交替抬腿",
    "2800": "杠铃坐姿交替抬腿（女）",
    # twisted leg raise (female) / twisted leg raise：同上。
    "2801": "转体抬腿",
    "2802": "转体抬腿（女）",
}

# 剥词阶段必须保护、不允许被剥离的词
NO_STRIP_EXTRA: set[str] = set()
